### DISCUSSION TITLE
Avoiding the Selenium password

### DISCUSSION THREAD

**Discussion by davida72** [robbrad/UKBinCollectionData#1368] [Ideas]
It's a pain to type 'secret' each time, but there's an environment variable to turn it off.

`VNC_NO_PASSWORD=1`

For example

```
  chrome1:
    image: selenium/node-chrome:4.20.0-20240505
    shm_size: 2gb
    networks:
      - devnet
    depends_on:
      - selenium-hub
    ports:
      - "7901:7900"
      - "5551:5555"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
    privileged: true
    restart: always
```
