### DISCUSSION TITLE
Attributes vs sensors

### DISCUSSION THREAD

**Discussion by Stutchbury** [robbrad/UKBinCollectionData#834] [Ideas]
First, thank you for this integration - exactly what I need. 

In HA (2024.10) I was trying to create a Dashboard Badge that only appeared 2 days before the recycling was due but it appears that 'attribute:' is not used in dashboard conditions, so having read the ([wrong](https://www.home-assistant.io/docs/scripts/conditions/#numeric-state-condition)) conditions docs, I raised an [issue](https://github.com/home-assistant/frontend/issues/22215).

It would appear UI conditions have a different set of [docs](https://rc.home-assistant.io/dashboards/conditional/#state) and one of the replies suggests HA developers are moving away from attributes towards sensors. It kinda makes sense to me if attributes remain as config values and runtime values become sensors.

Eg 'next_collection' and 'days' become sensors but not sure about 'colour'?

colour: red
next_collection: "2024-10-09"
days: 6
device_class: bin_collection_schedule
icon: mdi:trash-can
friendly_name: Recycling

Thoughts?

**Comment by robbrad** [comment]
I like what your saying 

Can you provide a versus example ?

I'm not quite understanding or finding it hard to picture what this looks like 

Thank you

**Reply by Stutchbury** [reply]
I'm not quite sure what you mean by a 'versus example' but it is possible to emulate a 'sensor' by creating a template based on an attribute (in configuration.yaml):

```
template:
  - sensor:
      - name: "Recycling Days"
        unit_of_measurement: "Days"
        device_class: "duration"
        state: "{{ state_attr('sensor.ukbins_recycling', 'days') }}"
```
This 'Recycling Days' sensor will now appear as an entity in the drop down list in the 'VISIBILITY' tab on Dashboard badges and cards: 

![image](https://github.com/user-attachments/assets/6d6c0270-c459-40f3-8648-5bef1680f8e7)

Without the template you would only be offered 'ukbins_recycling' in the drop down but of course the state of ukbins_recycling is not a numeric value so will always fail.

This is the yaml for that card:

```
type: entity
show_name: true
show_state: true
show_icon: true
entity: sensor.ukbins_recycling
color: ""
visibility:
  - condition: numeric_state
    entity: sensor.recycling_days
    below: 2
```
In the conditions section, you'd expect to be able to add an 'attribute: days' line (as you can in conditions elsewhere in HA) but this is not the case.

I can understand the 'sensors are runtime values vs attributes are config values' but have no idea how it would be implemented in code!

Hope this helps - happy to keep 'helping' :-)
