### DISCUSSION TITLE
HA notifications

### DISCUSSION THREAD

**Discussion by Cyruz143** [robbrad/UKBinCollectionData#959] [General]
Before using this I just had local calendar entries for my bins, automated notifications for them were quite simple, check the calendar event minus some hours so that I get the notification the day before.

I've been struggling a bit to find a way to mimic this behaviour using UKBCD as it doesn't add any calendar entries. I tried various bits like:

```yaml
trigger: state
entity_id:
  - sensor.refuse_bin
for:
  hours: 12
  minutes: 0
  seconds: 0
attribute: days
to: "1"
```

This didn't seem to fire, not sure why...

I tried going directly to the newer sensor:

```yaml
trigger: state
entity_id:
  - sensor.refuse_bin_days_until_collection
to: "1"
for:
  hours: 12
  minutes: 0
  seconds: 0
```

Didn't seem to fire either. Has anyone got a good working method to trigger notifications in HA?

**Comment by mrw298** [comment]
I set-up some template binary sensors to make it easier e.g. `binary_sensor.brown_bin_collection_tomorrow`:
```
{{ state_attr("sensor.brown_bin", "days") == 1 }}
```
I then have a reminder automation that fires at 8pm every night and checks what to remind me about!

**Reply by Cyruz143** [reply]
Ah right, that makes sense, although I guess I can go right to the new sensor rather than the old attributes like:

```yaml
{{ is_state("sensor.refuse_bin_days_until_collection", "1") }}
```

**Reply by mrw298** [reply]
that would work as well, my templates pre-date that change!

**Comment by robbrad** [comment]
@Cyruz143 I just added a calendar to the source code 😉

**Reply by Cyruz143** [reply]
Awesome, appreciate it and already re-setup my automations

**Comment by chronvas** [comment]
Here's what I use to combine all the calendar summaries to 1 and send a notificaiton the previous day of the collection (Monday):
```
alias: Monday Bins Calendar Summary Notification
description: Combine Bins calendars summary and send as notification
triggers:
  - at: "19:00:00"
    trigger: time
conditions:
  - condition: time
    weekday:
      - mon
actions:
  - target:
      entity_id:
        - calendar.__blue_recycling_paper_and_card_calendar
        - calendar.__brown_recycling_bottles_and_cans_calendar
        - calendar.__domestic_waste_calendar
        - calendar.__food_and_garden_waste_calendar
    data:
      duration:
        days: 7
    response_variable: calendar_events
    action: calendar.get_events
  - data:
      title: 🗑️ Bins tomorrow
      message: >
        {% set ns = namespace(text=[]) %} {% for cal in calendar_events.values()
        %}
          {% for event in cal.events %}
            {% if event.summary %}
              {% set ns.text = ns.text + ['. ' ~ event.summary] %}
            {% endif %}
          {% endfor %}
        {% endfor %} {{ ns.text | join('\n') }}
    action: notify.notify
mode: single
```
