### ISSUE TITLE
Please could you add East Hampshire County Council

### ISSUE THREAD

**Issue by Sparqx73** [robbrad/UKBinCollectionData#1014]
### Name of Council

East Hampshire County Council

### Example Address/Postcode

6 Cobbett Square, Bordon, Hampshire, GU35 0GD

### Additional Information

https://www.easthants.gov.uk/bin-collections/find-your-bin-calendar

### Verification

- [X] I''ve checked the [wiki](https://github.com/robbrad/UKBinCollectionData/wiki/Councils#contents) and verified that my council has not been added
- [X] I''ve checked that a request for my council does not already exist in the [Issues tracker](https://github.com/robbrad/UKBinCollectionData/issues?q=is%3Aopen+is%3Aissue+label%3A"council+request")
- [X] I have provided a tested working address/postcode/UPRN with bin collections available, as well as a link to the council''s website
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by joelis10** [comment]
+1 for EHDC

**Comment by TomK** [comment]
came here to add this request.  I have previously contacted East Hants and confirmed there is no API available. The collection service is managed by a third party which splits the region into numbered areas.  You have to find your area number using https://maps.easthants.gov.uk/ and download the appropriate calendar PDF.

using the example above `6 GU35 0GD` gives:
Bin Calendar: http://maps.easthants.gov.uk/JWWCalendars/2025/norse10.pdf
Garden Waste Calendar: http://maps.easthants.gov.uk/JWWCalendars/2025/G3.pdf

**Comment by robbrad** [comment]
Hi team @TomK / @joelis10 / @Sparqx73 can you try using https://github.com/robbrad/UKBinCollectionData/wiki/Councils#google-calendar-public

This will let you make a public Google Calendar, make it public (the ICS file link is what you need)

**Comment by joelis10** [comment]
just to double check @robbrad - are you asking for a public ICS calendar that has our bin days on it? I'm not sure if there is an official one but if that's what you're looking for, I'll have a look around

**Comment by robbrad** [comment]
@joelis10 either this or someone makes one ? - should be an easy task to put the data in a recurring event

Im going to close the issue we wont impliment due to PDFs - parsing PDFs is very unreliable - use Google calander approach instead

https://github.com/robbrad/UKBinCollectionData/wiki/Councils#google-calendar-public

**Comment by robbrad** [comment]
Closed issue but happy to support getting it working via discussions section

**Comment by joelis10** [comment]
While a recurring event would work, that doesn't include anomalies like holiday timings, which is why I wanted to get this working in the first place. I'll see if I can contact my council regarding an actual API or something.

**Comment by TomK** [comment]
I resorted to making a new calendar in my google account with repeating events. I made the few modifications for bank holidays this year and will update it when the next years calendar is released.

I'm just importing this using the Google Calendar integration, and writing a custom sensor for the next collection.

**Comment by TomK** [comment]
for anyone interested, i made the following template sensor which shows the next event from specified calendar, and the summaries of any other events that fall in that day:

![Image](https://github.com/user-attachments/assets/1e6a72be-016a-482f-85dd-9f0c06bec011)

![Image](https://github.com/user-attachments/assets/bab5a4b9-8fa3-4784-a07f-c33607e6ce42)

```yaml
template:   
  - trigger:
      - trigger: time_pattern
        # This will update every hour
        hours: "0"
        minutes: "0"
        seconds: "1"
    action:
      - action: calendar.get_events
        response_variable: agenda
        target:
          entity_id: calendar.waste_collection
        data:
          duration:
            hours: 192 # 8 days
    sensor:
      - name: "Next Waste Collection"
        unique_id: "next_waste_collection"
        icon: mdi:trash-can-outline
        attributes:
          agenda: "{{ agenda }}"
        state: |-
          {% if agenda['calendar.waste_collection'].events | count > 0 %}
          {% set next = agenda['calendar.waste_collection'].events[0].end %}
          {% for e in agenda['calendar.waste_collection'].events -%}
            {%- if e.end == next -%}
              {% if loop.index != 1 %}, {% endif %}{{ e.summary }}
            {%- endif -%}
          {%- endfor %}
          in {{ time_until((next|as_datetime)) }}
          {% endif %}

```
