### ISSUE TITLE
Raspberry Pi Docker Hub Image

### ISSUE THREAD

**Issue by rick165** [robbrad/UKBinCollectionData#563]
This is more of a request than an issue. 

Would it be possible to build a docker file for to run on the raspberry pi 4 (aarch64).

**Comment by rick165** [comment]
Managed to do this myself on a Raspberry Pi 4 using the following 

Navigate to the uk_bin_collection_api_server directory of the project and build ukbc_api_server 
`docker build -t ukbc_api_server .`

Then run it 
`docker run -p 8080:8080 ukbc_api_server`

The next part was finding an Arm64 image of selenium, I used this from docker seleniarm/standalone-chromium and built it using the following docker-compose.yml

```
version: '3'

services:
  selenium:
    image: seleniarm/standalone-chromium
    ports:
      - "4444:4444"

```
Once both were up and running I then navigated to the swagger ui and bingo!.
