### ISSUE TITLE
Would love to have this for North Somerset

### ISSUE THREAD

**Issue by B-Hartley** [robbrad/UKBinCollectionData#7]
Could you add North Somerset:

https://forms.n-somerset.gov.uk/Waste/CollectionSchedule
POST:
Content-Type: application/x-www-form-urlencoded

PreviousHouse   :   
PreviousPostcode  :  x
Postcode : x
SelectedUprn: 24034376

for example.

I'll have a going at doing it myself, but if you can do it, it might be quicker !

**Comment by B-Hartley** [comment]
going to have a stab with something like this.................

Haven't even tried to run it yet..............

#!/usr/bin/env python3
import json
from bs4 import BeautifulSoup

user_agent = 'Mozilla/5.0 (Windows NT 6.1; Win64; x64)'
headers = {'User-Agent': user_agent}

import urllib.parse
import urllib.request

url = 'https://forms.n-somerset.gov.uk/Waste/CollectionSchedule'
values = {'PreviousHouse' : '',
          'PreviousPostcode' : 'x',
          'Postcode' : 'x',
          'SelectedUprn' : '24032193' }

data = urllib.parse.urlencode(values)
req = urllib.request.Request(url, data)
req.add_header('User-Agent', user_agent)
response = urllib.request.urlopen(req)
fp = response.read()

html_data = fp.decode("utf8")

table_data = [[cell.text for cell in row("td")]
                         for row in BeautifulSoup(html_data)("tr")]

print json.dumps(dict(table_data))

**Comment by robbrad** [comment]
Added : https://github.com/robbrad/UKBinCollectionData/commit/cec930cef0d32ebb75ea986ed3578afa6f15c53a 

Enjoy 👍

**Comment by B-Hartley** [comment]
Thank you. That’s amazing. 
But I hadn’t got as far as thinking how I would use this. 
Do I use a command line sensor to run the script ?

**Comment by robbrad** [comment]
This depends on how you have your Home Assistant environment setup

My advice would be a cron job that runs to output the JSON to a file pirodically then have HA read it - avoids hammering your council for the same data.

https://community.home-assistant.io/t/reading-local-json-attribute-issue/94424/5?u=robbrad

**Comment by B-Hartley** [comment]
Ok. Sounds good. Thanks.

Bruce Hartley
Click Spares
07966 924863

________________________________

**Comment by B-Hartley** [comment]
I'm sure I'm being a bit stupid, but.......

I've setup the Cron Job and a mini web server as it is running on a different raspberry pi and I wanted to access it from my Hassio install.
But I can't figure out how to write the restful sensor to get the data out.

I've looked into json_paths and I've tried various things, but I don't seem to get the data I want into the sensor. 
Can you help me out?

Thanks
```

sensor:
  - platform: rest
    resource: http://192.168.11.58/bins.json
    name: Bin Day
    json_attributes:
      - BinType
      - collectionDate
    json_attributes_path: bins[0]
```

**Comment by B-Hartley** [comment]
OK, I went with this......
It is more than 255 characters, so I can't get the whole thing into one sensor.


```
sensor:
  - platform: rest
    resource: http://192.168.11.58/bins.json
    name: Bin Day Rubbish
    value_template: "{{ value_json.bins[0].collectionDate }}"
    json_attributes:
      - BinType
      - collectionDate
      - nextCollectionDate
    json_attributes_path: bins[0]
  - platform: rest
    resource: http://192.168.11.58/bins.json
    name: Bin Day Recycling
    value_template: "{{ value_json.bins[1].collectionDate }}"
    json_attributes:
      - BinType
      - collectionDate
      - nextCollectionDate
    json_attributes_path: bins[1]
  - platform: rest
    resource: http://192.168.11.58/bins.json
    name: Bin Day Garden
    value_template: "{{ value_json.bins[2].collectionDate }}"
    json_attributes:
      - BinType
      - collectionDate
      - nextCollectionDate
    json_attributes_path: bins[2]
```
