### ISSUE TITLE
 Migration handler not found for entry Home for uk_bin_collection 

### ISSUE THREAD

**Issue by Cyruz143** [robbrad/UKBinCollectionData#975]
### Home Assistant Version

2024.11.2

### Installation Method

Using HACS

### Issue Information

Updated to latest (0.114.1):

On start-up getting an error and all the entities are Unavailable

```yaml
Logger: homeassistant.config_entries
Source: config_entries.py:970
First occurred: 00:30:14 (1 occurrences)
Last logged: 00:30:14

Migration handler not found for entry Home for uk_bin_collection
```

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.12/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed
